version: "2"
services:
  guacd:
    image: "guacamole/guacd"
    container_name: guacd
    hostname: guacd
    restart: always
    ports:
      - "4822:4822"
    volumes:
      - /opt/guacamole/recordings:/opt/guacamole/recordings
    networks:
        default:
        internal:

  guacamole:
    image: "guacamole/guacamole:1.3.0"
    container_name: guacamole
    hostname: guacamole
    restart: always
    volumes:
      - "/opt/guacamole/guacamole:/data"
      - "/opt/guacamole/ROOT:/usr/local/tomcat/webapps/ROOT"
    ports:
      - "8080:8080"
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - MYSQL_HOSTNAME={{ guacamole_mysql_host }}
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD={{ guacamole_mysql_password }}
      - GUACAMOLE_HOME=/data
      - LOG_LEVEL=info
    depends_on:
      - mysql
      - guacd
    networks:
        default:
        internal:

  mysql:
    image: mariadb:10.4.12
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD={{ guacamole_mysql_password }}
      - MYSQL_DATABASE=guacamole_db
    volumes:
      - /opt/guacamole/init:/docker-entrypoint-initdb.d
      - /opt/guacamole/data:/var/lib/mysql
    networks:
        internal:
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

networks:
    default:
    internal:
        internal: true