[DEFAULT]
compute_driver=libvirt.LibvirtDriver
[libvirt]
virt_type=kvm
[pci]
device_spec = { "vendor_id": "{{ gpu_vendor_id }}" , "product_id": "{{ gpu_product_id }}"  }
alias = { "vendor_id":"{{ gpu_vendor_id }}", "product_id":"{{ gpu_product_id }}", "device_type":"type-PF", "name":"{{ gpu_alias }}" }
