site:
  title: Kinetic Documentation and Contribution Guide
  url: https://{{ docs_domain }}
  start_page: docs::index.adoc
content:
  sources:
  - url: {{ antora_docs_repo }}
    branches: master
ui: 
  bundle:
    url: {{ antora_theme_url }}
output:
  dir: /var/www/html
  clean: true
